// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function Reconnect():Promise<void>;

export function UpdateSerialConfig(arg1:string,arg2:number):Promise<void>;
