// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSerialPort():Promise<string>;

export function OpenSerialPort(arg1:string,arg2:number):Promise<string>;
