// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function UpdateSerialConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateSerialConfig'](arg1, arg2);
}
