// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseSerialPort() {
  return window['go']['main']['App']['CloseSerialPort']();
}

export function OpenSerialPort(arg1, arg2) {
  return window['go']['main']['App']['OpenSerialPort'](arg1, arg2);
}
